# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wenshuran/hdcourse/test_zynqnet/zynqnet_vivado/zynqnet_vivado.cache/wt [current_project]
set_property parent.project_path /home/wenshuran/hdcourse/test_zynqnet/zynqnet_vivado/zynqnet_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/wenshuran/hdcourse/test_zynqnet/test_zynq/solution1/impl/ip [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/wenshuran/hdcourse/test_zynqnet/test_zynq/solution1/impl/ip/tmp.srcs/sources_1/ip/fpga_top_ap_fadd_3_full_dsp_32/fpga_top_ap_fadd_3_full_dsp_32.xci
set_property is_locked true [get_files /home/wenshuran/hdcourse/test_zynqnet/test_zynq/solution1/impl/ip/tmp.srcs/sources_1/ip/fpga_top_ap_fadd_3_full_dsp_32/fpga_top_ap_fadd_3_full_dsp_32.xci]

synth_design -top fpga_top_ap_fadd_3_full_dsp_32 -part xc7z020clg484-1
write_checkpoint -noxdef fpga_top_ap_fadd_3_full_dsp_32.dcp
catch { report_utilization -file fpga_top_ap_fadd_3_full_dsp_32_utilization_synth.rpt -pb fpga_top_ap_fadd_3_full_dsp_32_utilization_synth.pb }
