// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _fpga_top_reg_float_s_HH_
#define _fpga_top_reg_float_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct fpga_top_reg_float_s : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > in_r;
    sc_out< sc_lv<32> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    fpga_top_reg_float_s(sc_module_name name);
    SC_HAS_PROCESS(fpga_top_reg_float_s);

    ~fpga_top_reg_float_s();

    sc_trace_file* mVcdFile;

    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
};

}

using namespace ap_rtl;

#endif
